# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: meriem@gmail.com
author_name: meriem
has_binder: true
has_settings: true
kind: frontend
labextension_name: kernel_specs_panel
project_short_description: A JupyterLab extension.
python_name: kernel_specs_panel
repository: ''
test: true

